services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: ${POSTGRES_CONTAINER_NAME:-python_drf_101_postgres_container}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-54321}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: